[package]
name = "japanese_text_analyzer"
version = "0.1.0"
edition = "2021"

[dependencies]
sudachi = { git = "https://github.com/Kuuuube/sudachi.rs" }
zstd-safe = { version = "7.1.0", features = ["experimental", "std"] }
